services:
  - type: web
    name: iotanalyser
    env: docker
    branch: main
    plan: starter
    buildCommand: ""
    startCommand: ""   # Dockerfile ENTRYPOINT will run
    dockerfilePath: ./iotanalyser/Dockerfile # Corrected path
    autoDeploy: true
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: h2
      # Add these lines to inject your secrets
      - key: OPENWEATHERMAP_API_KEY
        fromSecret: true
      - key: JWT_SECRET
        fromSecret: true